services:
    conekta.form.type:
        class: Scastells\ConektaBundle\Form\Type\ConektaType
        arguments:
            - @router
            - %conekta.controler.route.name%
        tags:
            - { name: form.type, alias: conekta_view }

    conekta.manager:
        class: Scastells\ConektaBundle\Services\ConektaManager
        arguments:
            - @payment.event.dispatcher
            - @contekta.wrapper

    conekta.oxxo_routes.loader:
        class: Scastells\ConektaBundle\Router\ConektaOxxoRouterLoader
        arguments:
            - %conekta.oxxo.controller.route.name%
            - %conekta.oxxo_execute.route%
            - %conekta.oxxo_notify.route%
            - %conekta.oxxo.controller.route.notify.name%
        tags:
            - { name: routing.loader }

    spei_routes.loader:
            class: Scastells\ConektaBundle\Router\SpeiRouterLoader
            arguments:
                - %conekta.spei.controller.route.name%
                - %conekta.spei_execute.route%
                - %conekta.spei_notify.route%
                - %conekta.spei.controller.route.notify.name%
            tags:
                - { name: routing.loader }

    conekta_routes.loader:
        class: Scastells\ConektaBundle\Router\ConektaRouterLoader
        arguments:
            - %conekta.controller.route%
        tags:
            - { name: routing.loader }

    contekta.wrapper:
        class: Scastells\ConektaBundle\Services\ConektaWrapper
        arguments:
              - %conekta.currency%
              - %conekta.api.key%

    conekta.event.listener:
        class: Scastells\ConektaBundle\EventListener\ConektaListener
        arguments:
            - @mailer
            - @templating
            - @translator
            - @doctrine.orm.entity_manager
            - @baseecommerce.core.purchase.services.order_manager
        tags:
            - { name: kernel.event_listener, event: payment.order.done, method: onPaymentOrderDone }
            - { name: kernel.event_listener, event: payment.order.success, method: onPaymentOrderSucces }


    conekta.twig.extension:
            class: Scastells\ConektaBundle\Twig\ConektaExtension
            arguments:
                stripe.public.key: %conekta.public.key%
                form.factory: @form.factory
                payment.bridge: @payment.bridge
                view_template: %conekta.templates.view_template%
                scripts_template: %conekta.templates.scripts_template%
            tags:
                - { name: twig.extension }
