services:
    conekta.manager:
        class: Scastells\ConektaBundle\Services\ConektaManager
        arguments:
            - @payment.event.dispatcher
            - @contekta.wrapper

    conekta.oxxo_routes.loader:
        class: Scastells\ConektaBundle\Router\ConektaOxxoRouterLoader
        arguments:
            - %conekta.oxxo.controller.route.name%
            - %conekta.oxxo_execute.route%
            - %conekta.oxxo_notify.route%
            - %conekta.oxxo.controller.route.notify.name%
        tags:
            - { name: routing.loader }

    contekta.wrapper:
        class: Scastells\ConektaBundle\Services\ConektaWrapper
        arguments:
              - %conekta.currency%
              - %conekta.api.key%

    pagosonline_gateway.event.listener:
        class: Scastells\ConektaBundle\EventListener\ConektaListener
        arguments:
            - @mailer
            - @templating
            - @translator
            - @doctrine.orm.entity_manager
            - @baseecommerce.core.purchase.services.order_manager
        tags:
            - { name: kernel.event_listener, event: payment.order.done, method: onPaymentOrderDone }
